-- Run this SQL in Supabase to create settings table

CREATE TABLE IF NOT EXISTS app_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert default start datetime if not exists
INSERT INTO app_settings (key, value) 
VALUES ('sehri_start_datetime', NOW()::text)
ON CONFLICT (key) DO NOTHING;

-- Enable RLS
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read and authenticated write
CREATE POLICY "Allow public read settings" ON app_settings FOR SELECT USING (true);
CREATE POLICY "Allow public update settings" ON app_settings FOR UPDATE USING (true);
CREATE POLICY "Allow public insert settings" ON app_settings FOR INSERT WITH CHECK (true);
